version: 2.1

workflows:
  build-and-test:
    jobs:
      - test:
          context: OPEN_SOURCE
          filters:
            branches:
              only:
                - develop

jobs:
  # Test
  test:
    docker:
      - image: quay.io/dafiti/k8s-values-updater:develop
    steps:
      - add_ssh_keys:
          fingerprints:
            - "79:4a:52:b0:4f:1a:29:46:5d:a6:f2:77:9d:7b:77:3a"
      - checkout
      - setup_remote_docker
      - run:
          name: Try to commit and push
          command: |
            # Will remove this in the future
            ssh-keyscan -H github.com > ~/.ssh/known_hosts
            #
            # Will try https
            /k8s-values-updater bump \
              --e "d.ploy@dafiti.com.br" \
              --t "$(echo ${CIRCLE_SHA1} | head -c7)" \
              # Remove this when copying this snippet
              --dir-path "example"
            #
            # Remove this part when copying this snippet
            # Will try ssh
            /k8s-values-updater bump \
              --e "d.ploy@dafiti.com.br" \
              --t "$(echo ${CIRCLE_SHA1} | head -c7)" \
              # Remove this when copying this snippet
              --force-ssh \
              --dir-path "example"
