version: 2.1

workflows:
  build-and-test:
    jobs:
      - test:
          context: OPEN_SOURCE
          filters:
            branches:
              only:
                - develop
jobs:
  # Test
  test:
    docker:
      - image: quay.io/dafiti/k8s-values-updater:develop
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Try to commit and push
          command: |
            /k8s-values-updater bump -e d.ploy@dafiti.com.br -t $(echo ${CIRCLE_SHA1} | head -c7) --dir-path example
